/**
 * Loading the fixtures generated by `scripts/export_golden.py`.
 *
 * The division of labour matters. The 60 Python tests keep enforcing the real
 * invariants against real data -- calibration MAE, scoring against nflverse,
 * every player resolving to a unique id. These tests enforce only one thing:
 * that the TypeScript agrees with the Python. Both jobs are needed.
 */

import { readFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

import type { ColumnarTable } from "../lib/bundle";
import type { Bundle } from "../lib/board";
import type { LeagueConfig } from "../lib/types";

const HERE = dirname(fileURLToPath(import.meta.url));
const GOLDEN_DIR = join(HERE, "golden");
const BUNDLE_DIR = join(HERE, "..", "..", "data", "v2_export");

export interface GoldenCurve {
  grid: number[];
  mean: number[];
  sd: number[];
  games: number[];
  n: number;
}

export interface GoldenFixture {
  name: string;
  format: string;
  league: LeagueConfig;
  curves: Record<string, GoldenCurve>;
  projections: {
    player_id: string;
    pos: string;
    pos_rank: number;
    proj_points: number;
    sd: number;
    games: number;
  }[];
  projections_raw: {
    player_id: string;
    proj_raw: number;
    sd_raw: number;
    games_raw: number;
  }[];
  replacement: Record<string, number>;
  vor: { player_id: string; vor: number; vor_rank: number }[];
  tiers: {
    player_id: string;
    pos: string;
    tier: number;
    tier_size: number;
    tier_points: number;
  }[];
  tier_counts: Record<string, number>;
  lineups: { roster: { pos: string; proj_points: number }[]; points: number }[];
  survival: {
    pick: number;
    n_sims: number;
    values: { player_id: string; p_available: number }[];
  };
}

/** Every fixture, in the order `export_golden.py` writes them. */
export const FIXTURE_NAMES = [
  "reference_ppr_14",
  "half_ppr_10",
  "superflex_12",
  "no_flex_8",
] as const;

function readJson<T>(path: string): T {
  return JSON.parse(readFileSync(path, "utf-8")) as T;
}

export function loadFixture(name: string): GoldenFixture {
  return readJson<GoldenFixture>(join(GOLDEN_DIR, `${name}.json`));
}

export function loadTable(name: string): ColumnarTable {
  return readJson<ColumnarTable>(join(BUNDLE_DIR, `${name}.json`));
}

export function loadManifest(): { team_nicknames: Record<string, string> } {
  return readJson(join(BUNDLE_DIR, "manifest.json"));
}

/** Assemble the bundle a fixture's format needs. */
export function loadBundle(format: string): Bundle {
  return {
    board: loadTable(`board_${format}`),
    training: loadTable(`training_${format}`),
    kickerComponents: loadTable("kicker_components"),
    dstComponents: loadTable("dst_components"),
    schedule: loadTable("schedule_difficulty"),
    teamNicknames: loadManifest().team_nicknames,
  };
}

/** Players sitting on an exact rounding tie, split by which quantity ties. */
export interface TieSets {
  /** Ties in projected points. These propagate into VOR and tier boundaries. */
  points: Set<string>;
  sd: Set<string>;
  /** Ties in games played. Display-only, and by far the most common. */
  games: Set<string>;
  any: Set<string>;
}

/**
 * Find the rounding ties.
 *
 * Rounding to one decimal is cosmetic, but `84.85` is a genuine tie and a
 * 1e-14 difference in float summation order sends it to 84.8 in one
 * implementation and 84.9 in the other. Neither is wrong, and matching
 * sklearn's Cython accumulation bit-for-bit is not realistically achievable.
 *
 * They are split by quantity because the quantities matter differently.
 * Projected points feed VOR and tiering, so ties there are worth capping
 * tightly. Games played is fitted on small integers, so pooled block means land
 * on a quarter constantly -- ties are the norm rather than a smell, and nothing
 * downstream reads the value.
 */
export function tieBoundaryPlayers(fixture: GoldenFixture, epsilon = 1e-9): TieSets {
  const isTie = (v: number | null) => {
    if (v === null || v === undefined) return false;
    const scaled = v * 10;
    return Math.abs(scaled - Math.floor(scaled) - 0.5) < epsilon;
  };

  const sets: TieSets = { points: new Set(), sd: new Set(), games: new Set(), any: new Set() };
  for (const row of fixture.projections_raw) {
    if (isTie(row.proj_raw)) sets.points.add(row.player_id);
    if (isTie(row.sd_raw)) sets.sd.add(row.player_id);
    if (isTie(row.games_raw)) sets.games.add(row.player_id);
  }
  for (const s of [sets.points, sets.sd, sets.games]) {
    for (const id of s) sets.any.add(id);
  }
  return sets;
}

/** Index a list of records by player id. */
export function byPlayer<T extends { player_id: string }>(rows: T[]): Map<string, T> {
  return new Map(rows.map((r) => [r.player_id, r]));
}
